/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/app-header/AppHeader.vue')['default']
    AudioPlayer: typeof import('./src/components/AudioPlayer.vue')['default']
    Button: typeof import('./src/components/button/Button.vue')['default']
    EmptyState: typeof import('./src/components/empty-state/EmptyState.vue')['default']
    GeoStatusCard: typeof import('./src/components/geo-status-card/GeoStatusCard.vue')['default']
    Loading: typeof import('./src/components/loading/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/search-bar/SearchBar.vue')['default']
    StationCard: typeof import('./src/components/station-card/StationCard.vue')['default']
    StatusCard: typeof import('./src/components/status-card/StatusCard.vue')['default']
    TabBar: typeof import('./src/components/tab-bar/TabBar.vue')['default']
  }
}
