/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioPlayer: typeof import('./../components/AudioPlayer.vue')['default']
    EmptyState: typeof import('./../components/EmptyState.vue')['default']
    GeoStatusCard: typeof import('./../components/geo-status-card/GeoStatusCard.vue')['default']
    Loading: typeof import('./../components/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
