/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AudioPlayer: typeof import('./../components/AudioPlayer.vue')['default']
    Button: typeof import('./../components/button/Button.vue')['default']
    CommonAppHeader: typeof import('./../components/common-app-header/CommonAppHeader.vue')['default']
    CommonAppTabBar: typeof import('./../components/common-app-tab-bar/CommonAppTabBar.vue')['default']
    CommonSearchBar: typeof import('./../components/common-search-bar/CommonSearchBar.vue')['default']
    EmptyState: typeof import('./../components/EmptyState.vue')['default']
    GeoStatusCard: typeof import('./../components/geo-status-card/GeoStatusCard.vue')['default']
    LayoutsMainLayout: typeof import('./../components/layouts-main-layout/LayoutsMainLayout.vue')['default']
    Loading: typeof import('./../components/Loading.vue')['default']
    PagesHome: typeof import('./../components/pages-home/PagesHome.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StationCard: typeof import('./../components/station-card/StationCard.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanDialog: typeof import('vant/es')['Dialog']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanToast: typeof import('vant/es')['Toast']
  }
}
